import { AgentPreferences, Deal } from '@/types';

export const DEFAULT_PREFERENCES: AgentPreferences = {
  senderName: '',
  role: 'AE',
  tone: 'friendly',
  style: 'short',
  productDescription: 'We provide a RevOps automation platform that helps B2B teams clean their CRM and run better playbooks.',
  calendarLink: 'https://calendly.com/jdoe/intro',
  language: 'en',
};

export const DEFAULT_USER_PROFILE = {
  name: 'John Doe',
  email: 'john@drift.app',
  title: 'Senior Account Executive',
  country: 'United States',
  language: 'en',
  timezone: 'EST',
  notifications: {
    emailDigest: true,
    pushDesktop: false,
    marketing: false,
  },
  stalledThresholdDays: 14,
  riskWeightAmount: 0.4,
  riskWeightStage: 0.3,
  riskWeightInactivity: 0.2,
  riskWeightNotes: 0.1,
  highValueThreshold: 50000,
  riskyStages: [],
  riskKeywords: [],
};

export const MOCK_DEALS: Deal[] = [
  {
    id: '1',
    name: 'Enterprise License Expansion',
    companyName: 'Acme Corp',
    contactName: 'Sarah Jenkins',
    priority: 'high',
    stage: 'Negotiation',
    nextStep: 'Legal review of MSA',
    amount: 45000,
    currency: 'USD',
    daysInStage: 12,
    daysInactive: 5,
    crmUrl: '#',
    lastActivityDate: '2023-10-25T10:00:00Z',
    notes: 'Sarah is pushing for a discount on the annual plan. Need to verify with finance if we can do 10% off for 2-year commit.',
    aiFollowUp: undefined,
  },
  {
    id: '2',
    name: 'Q4 Marketing Tooling',
    companyName: 'TechFlow',
    contactName: 'Mike Ross',
    priority: 'high',
    stage: 'Qualified to Buy',
    nextStep: null,
    amount: 28000,
    currency: 'USD',
    daysInStage: 24,
    daysInactive: 14,
    crmUrl: '#',
    lastActivityDate: '2023-10-15T14:30:00Z',
    notes: 'Mike was excited about the demo but ghosted after receiving the pricing deck. Might need to re-sell value.',
  },
  {
    id: '3',
    name: 'Global Team Access',
    companyName: 'Globex Inc',
    contactName: 'Hank Scorpio',
    priority: 'medium',
    stage: 'Proposal Sent',
    nextStep: 'Waiting for feedback',
    amount: 15000,
    currency: 'EUR',
    daysInStage: 8,
    daysInactive: 8,
    crmUrl: '#',
    lastActivityDate: '2023-10-22T09:00:00Z',
    notes: 'Sent the proposal last Tuesday. Hank mentioned he is traveling this week.',
  },
  {
    id: '4',
    name: 'Startup Plan',
    companyName: 'Pied Piper',
    contactName: 'Richard Hendricks',
    priority: 'low',
    stage: 'Discovery',
    nextStep: 'Schedule demo',
    amount: 5000,
    currency: 'USD',
    daysInStage: 45,
    daysInactive: 30,
    crmUrl: '#',
    lastActivityDate: '2023-09-29T11:00:00Z',
    notes: 'Low priority lead. They are very early stage. Only follow up if I have spare time.',
  },
  {
    id: '5',
    name: 'Data Migration Project',
    companyName: 'Soylent Corp',
    contactName: 'Charlton Heston',
    priority: 'medium',
    stage: 'Evaluation',
    nextStep: 'Technical POC',
    amount: 62000,
    currency: 'USD',
    daysInStage: 18,
    daysInactive: 3,
    crmUrl: '#',
    lastActivityDate: '2023-10-27T16:45:00Z',
    notes: 'Technical team is evaluating the API limits. Need to send them the updated documentation.',
  },
  {
    id: '6',
    name: 'Q1 Security Audit',
    companyName: 'CyberDyne Systems',
    contactName: 'Miles Bennett',
    priority: 'high',
    stage: 'Negotiation',
    nextStep: 'Procurement approval',
    amount: 85000,
    currency: 'USD',
    daysInStage: 5,
    daysInactive: 2,
    crmUrl: '#',
    lastActivityDate: '2023-10-28T10:00:00Z',
    notes: 'Miles is on board, just dealing with red tape in procurement.',
  },
  {
    id: '7',
    name: 'Cloud Infrastructure Upgrade',
    companyName: 'Massive Dynamic',
    contactName: 'Nina Sharp',
    priority: 'medium',
    stage: 'Evaluation',
    nextStep: 'Security questionnaire',
    amount: 120000,
    currency: 'USD',
    daysInStage: 15,
    daysInactive: 9,
    crmUrl: '#',
    lastActivityDate: '2023-10-20T10:00:00Z',
    notes: 'They have a very long security questionnaire. Need engineering help to fill it out.',
  },
  {
    id: '8',
    name: 'API Integration',
    companyName: 'Hooli',
    contactName: 'Gavin Belson',
    priority: 'low',
    stage: 'Discovery',
    nextStep: 'Intro call',
    amount: 12000,
    currency: 'USD',
    daysInStage: 2,
    daysInactive: 1,
    crmUrl: '#',
    lastActivityDate: '2023-10-30T10:00:00Z',
    notes: 'Inbound lead from the website. Seems small but has potential.',
  },
  {
    id: '9',
    name: 'Retail POS System',
    companyName: 'Buy n Large',
    contactName: 'Shelby Forthright',
    priority: 'high',
    stage: 'Proposal Sent',
    nextStep: 'Review proposal with board',
    amount: 250000,
    currency: 'USD',
    daysInStage: 10,
    daysInactive: 6,
    crmUrl: '#',
    lastActivityDate: '2023-10-24T10:00:00Z',
    notes: 'Huge opportunity. Competitors are sniffing around. Stay close.',
  },
  {
    id: '10',
    name: 'Logistics Optimization',
    companyName: 'Planet Express',
    contactName: 'Hubert Farnsworth',
    priority: 'medium',
    stage: 'Qualified to Buy',
    nextStep: 'Finalize scope',
    amount: 35000,
    currency: 'USD',
    daysInStage: 20,
    daysInactive: 15,
    crmUrl: '#',
    lastActivityDate: '2023-10-15T10:00:00Z',
    notes: 'Hubert is forgetful. Need to remind him about the scope document.',
  },
  {
    id: '11',
    name: 'Government Contract',
    companyName: 'Tyrell Corp',
    contactName: 'Eldon Tyrell',
    priority: 'high',
    stage: 'Negotiation',
    nextStep: 'Awaiting signature',
    amount: 500000,
    currency: 'USD',
    daysInStage: 30,
    daysInactive: 25,
    crmUrl: '#',
    lastActivityDate: '2023-10-05T10:00:00Z',
    notes: 'Stuck in legal hell. Need to nudge their general counsel.',
  },
  {
    id: '12',
    name: 'Healthcare Compliance',
    companyName: 'Umbrella Corp',
    contactName: 'Albert Wesker',
    priority: 'low',
    stage: 'Discovery',
    nextStep: 'Send case studies',
    amount: 18000,
    currency: 'USD',
    daysInStage: 4,
    daysInactive: 4,
    crmUrl: '#',
    lastActivityDate: '2023-10-26T10:00:00Z',
    notes: 'Asked for case studies specifically about bio-tech.',
  },
  {
    id: '13',
    name: 'E-commerce Platform',
    companyName: 'Stark Industries',
    contactName: 'Pepper Potts',
    priority: 'high',
    stage: 'Evaluation',
    nextStep: 'Tech demo for Tony',
    amount: 150000,
    currency: 'USD',
    daysInStage: 12,
    daysInactive: 3,
    crmUrl: '#',
    lastActivityDate: '2023-10-27T10:00:00Z',
    notes: 'Pepper loves the UI, but Tony needs to approve the backend architecture.',
  },
  {
    id: '14',
    name: 'Media Archiving',
    companyName: 'Wayne Enterprises',
    contactName: 'Lucius Fox',
    priority: 'medium',
    stage: 'Qualified to Buy',
    nextStep: 'Budget approval',
    amount: 75000,
    currency: 'USD',
    daysInStage: 14,
    daysInactive: 10,
    crmUrl: '#',
    lastActivityDate: '2023-10-20T10:00:00Z',
    notes: 'Lucius is busy with R&D. Need to respect his time but keep moving.',
  },
  {
    id: '15',
    name: 'Hospitality Suite',
    companyName: 'Nakatomi Trading',
    contactName: 'Holly Gennaro',
    priority: 'low',
    stage: 'Discovery',
    nextStep: 'Reschedule call',
    amount: 10000,
    currency: 'USD',
    daysInStage: 40,
    daysInactive: 35,
    crmUrl: '#',
    lastActivityDate: '2023-09-25T10:00:00Z',
    notes: 'Ghosted after the first call. Probably dead.',
  },
  {
    id: '16',
    name: 'Financial Audit Tool',
    companyName: 'Gringotts',
    contactName: 'Griphook',
    priority: 'high',
    stage: 'Negotiation',
    nextStep: 'Security clearance',
    amount: 90000,
    currency: 'GBP',
    daysInStage: 22,
    daysInactive: 12,
    crmUrl: '#',
    lastActivityDate: '2023-10-18T10:00:00Z',
    notes: 'Very strict security requirements. They are worried about data theft.',
  },
  {
    id: '17',
    name: 'Training Simulator',
    companyName: 'InGen',
    contactName: 'John Hammond',
    priority: 'medium',
    stage: 'Proposal Sent',
    nextStep: 'Cost reduction',
    amount: 40000,
    currency: 'USD',
    daysInStage: 7,
    daysInactive: 7,
    crmUrl: '#',
    lastActivityDate: '2023-10-23T10:00:00Z',
    notes: 'Spared no expense... except on software. He wants a discount.',
  },
  {
    id: '18',
    name: 'Automated Factory',
    companyName: 'Wonka Industries',
    contactName: 'Charlie Bucket',
    priority: 'low',
    stage: 'Discovery',
    nextStep: 'Intro meeting',
    amount: 15000,
    currency: 'USD',
    daysInStage: 3,
    daysInactive: 3,
    crmUrl: '#',
    lastActivityDate: '2023-10-27T10:00:00Z',
    notes: 'New CEO, seems open to modernizing the factory floor.',
  },
  {
    id: '19',
    name: 'Server Cooling',
    companyName: 'Aperture Science',
    contactName: 'Cave Johnson',
    priority: 'high',
    stage: 'Evaluation',
    nextStep: 'Lab testing',
    amount: 60000,
    currency: 'USD',
    daysInStage: 25,
    daysInactive: 18,
    crmUrl: '#',
    lastActivityDate: '2023-10-12T10:00:00Z',
    notes: 'We do what we must because we can. They are testing our limits.',
  },
  {
    id: '20',
    name: 'Paper Supply Chain',
    companyName: 'Dunder Mifflin',
    contactName: 'Dwight Schrute',
    priority: 'medium',
    stage: 'Qualified to Buy',
    nextStep: 'Assistant to the RM approval',
    amount: 22000,
    currency: 'USD',
    daysInStage: 9,
    daysInactive: 2,
    crmUrl: '#',
    lastActivityDate: '2023-10-28T10:00:00Z',
    notes: 'Dwight is very particular about the specific features. Bears, Beets, Battlestar Galactica.',
  },
  {
    id: '21',
    name: 'Gaming Network',
    companyName: 'Encom',
    contactName: 'Kevin Flynn',
    priority: 'medium',
    stage: 'Discovery',
    nextStep: 'Technical deep dive',
    amount: 55000,
    currency: 'USD',
    daysInStage: 11,
    daysInactive: 6,
    crmUrl: '#',
    lastActivityDate: '2023-10-24T10:00:00Z',
    notes: 'Kevin wants to know if our system can handle the Grid traffic.',
  },
  {
    id: '22',
    name: 'Robotics Control',
    companyName: 'U.S. Robots',
    contactName: 'Susan Calvin',
    priority: 'high',
    stage: 'Negotiation',
    nextStep: 'Ethics committee review',
    amount: 300000,
    currency: 'USD',
    daysInStage: 40,
    daysInactive: 10,
    crmUrl: '#',
    lastActivityDate: '2023-10-20T10:00:00Z',
    notes: 'Susan is worried about the Three Laws implementation.',
  },
  {
    id: '23',
    name: 'Shipping Logistics',
    companyName: 'Blue Sun',
    contactName: 'River Tam',
    priority: 'low',
    stage: 'Discovery',
    nextStep: 'Unknown',
    amount: 12000,
    currency: 'USD',
    daysInStage: 50,
    daysInactive: 45,
    crmUrl: '#',
    lastActivityDate: '2023-09-15T10:00:00Z',
    notes: 'Contact is very cryptic. Hard to get a straight answer.',
  },
  {
    id: '24',
    name: 'Energy Grid',
    companyName: 'Shinra Electric',
    contactName: 'Rufus Shinra',
    priority: 'high',
    stage: 'Proposal Sent',
    nextStep: 'Board meeting',
    amount: 800000,
    currency: 'USD',
    daysInStage: 15,
    daysInactive: 8,
    crmUrl: '#',
    lastActivityDate: '2023-10-22T10:00:00Z',
    notes: 'They have endless budget but dubious ethics. Proceed with caution.',
  },
  {
    id: '25',
    name: 'Operating System',
    companyName: 'OS1',
    contactName: 'Theodore Twombly',
    priority: 'medium',
    stage: 'Evaluation',
    nextStep: 'User testing',
    amount: 25000,
    currency: 'USD',
    daysInStage: 5,
    daysInactive: 1,
    crmUrl: '#',
    lastActivityDate: '2023-10-29T10:00:00Z',
    notes: 'Theodore is writing personal letters using our tool. Interesting use case.',
  }
];
